version: '3.8'

services:
    bot:
        build:
            context: './bot'
        environment:
            DISCORD_PUBLIC_KEY: '${DISCORD_PUBLIC_KEY}'
            DISCORD_TOKEN: '${DISCORD_TOKEN}'
            DISCORD_GUILD_ID: '${DISCORD_GUILD_ID}'
            DISCORD_APPLICATION_ID: '${DISCORD_APPLICATION_ID}'
            DISCORD_CLIENT_ID: '${DISCORD_CLIENT_ID}'
            DISCORD_CLIENT_SECRET: '${DISCORD_CLIENT_SECRET}'
            REDIRECT_URI: '${REDIRECT_URI}'
            FILL_DATABASE: '${FILL_DATABASE}'
            API_SECRET: '${API_SECRET}'
            ANNOUNCEMENT_CHANNEL: '${ANNOUNCEMENT_CHANNEL}'
            CUP_STORAGE: '/data/cup-storage'
            MONGO_URL: 'mongodb://db:27017/dbtcup'
        volumes:
            - './volumes/cups:/data/cup-storage'
        restart: 'always'
    front:
        build:
            context: './front'
            args:
                API_HOST: 'bot'
    db:
        image: 'mongo:latest'
        volumes:
            - './volumes/db:/data/db'
