const FETCHME_REQUEST = "FETCHME_REQUEST";
const FETCHME_FAILURE = "FETCHME_FAILURE";
const FETCHME_SUCCESS = "FETCHME_SUCCESS";

export default {
  FETCHME_REQUEST,
  FETCHME_FAILURE,
  FETCHME_SUCCESS,
};
